apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.buildConfig.name }}
  labels:
    {{- include "bmfm-sm-inference-chart.labels" . | nindent 4 }}
    part-of: {{ .Release.Name }}
spec:
  source:
    git:
      uri: {{ .Values.buildConfig.gitUri }}
      ref: {{ .Values.buildConfig.gitRef }}
  strategy:
    type: {{ .Values.buildConfig.strategy }}
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
